crumpet/backtests/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from crumpet.backtests import views

urlpatterns = [
    url(
        r"^$",
        login_required(views.BacktestingView.as_view(
            template_name="backtests/backtesting.html"
        )),
        name="backtesting"
    ),
    url(
        r"^live/$",
        login_required(views.LiveTestView.as_view(
            template_name="backtests/livetest.html"
        )),
        name="livetest"
    ),
]

crumpet/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(
        r"^account/$",
        login_required(views.AccountPageView.as_view(
            template_name="crumpet/pages/account.html"
        )),
        name="account"
    ),
    url(
        r"^portfolio/$",
        login_required(views.PortfolioView.as_view(
            template_name="crumpet/pages/portfolio.html"
        )),
        name="portfolio"
    ),
    url(
        r"^$",
        views.DashboardView.as_view(),
        name="dashboard"
    )
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from project import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^", include("crumpet.urls", namespace="crumpet")),
    url(r"^backtests/", include("crumpet.backtests.urls", namespace="backtests")),
    url(r'^accounts/', include('allauth.urls'))
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r"^django-toolbar/", include(debug_toolbar.urls)),
    ]

crumpet/backtests/forms.py
from django import forms

from django.utils.translation import ugettext_lazy as _

from crumpet.profiles import constants


class ToTheMoonStrategyForm(forms.Form):
    exchange = forms.ChoiceField(
        required=False,
        label=_("Exchange"),
        choices=constants.CRYPTO_EXCHANGES
    )
    instrument = forms.ChoiceField(
        required=False,
        label=_("Instrument"),
        choices=constants.INSTRUMENTS
    )
    mode = forms.ChoiceField(
        required=False,
        label=_("Mode"),
        choices=constants.MODES
    )
    exchange_period = forms.ChoiceField(
        required=False,
        label=_("Period"),
        choices=constants.EXCHANGE_PERIODS
    )
    start_date = forms.DateField(
        required=False,
        widget=forms.DateInput(
            attrs={
                "type": "date",
                "customDate": "true",
                "placeholder": _("yyyy/mm/dd"),
                "required": "required"
            }
        )
    )
    end_date = forms.DateField(
        required=False,
        widget=forms.DateInput(
            attrs={
                "type": "date",
                "customDate": "true",
                "placeholder": _("yyyy/mm/dd"),
                "required": "required"
            }
        )
    )
    trading_fee = forms.CharField(
        required=False,
        label=_("Trading Fee (%)"),
        widget=forms.TextInput(
            attrs={
                "placeholder": _("0.1%")
            }
        ),
        max_length=100

    )
    strategy = forms.ChoiceField(
        required=False,
        label=_("Strategy"),
        choices=constants.STRATEGIES
    )

    sma_period = forms.CharField(
        required=False,
        label=_("Simple Moving Average"),
        widget=forms.TextInput(
            attrs={
                "placeholder": _("25")
            }
        ),
        max_length=100
    )

    ema_period = forms.CharField(
        required=False,
        label=_("Exponetial Moving Average"),
        widget=forms.TextInput(
            attrs={
                "placeholder": _("13")
            }
        ),
        max_length=100
    )

crumpet/backtests/views.py
import simplejson
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import FormView

from crumpet.backtests import forms
from crumpet.tradebot import Tradebot, Wallet


class BacktestingView(FormView):
    form_class = forms.ToTheMoonStrategyForm
    template_name = "backtests/backtesting.html"

    def form_valid(self, form):
        context = self.get_context_data()
        exchange = form.cleaned_data['exchange']
        instrument = form.cleaned_data['instrument']
        period = form.cleaned_data['exchange_period']

        if form.cleaned_data['trading_fee']:
            trading_fee = float(form.cleaned_data['trading_fee'])
            wallet = Wallet(assets=100, currency=100, instrument=instrument, fee=trading_fee)
        else:
            wallet = Wallet(assets=100, currency=100, instrument=instrument)

        strategy = form.cleaned_data['strategy']
        mode = form.cleaned_data['mode']
        start_date = form.cleaned_data['start_date']
        end_date = form.cleaned_data['end_date']
        sma_period = form.cleaned_data['sma_period']
        ema_period = form.cleaned_data['ema_period']

        bot = Tradebot(
            mode=mode,
            wallet=wallet,
            strategy=strategy,
            instrument=instrument, period=int(period),
            start_date=start_date, end_date=end_date,
            sma_period=sma_period, ema_period=ema_period)
        data = bot.start()

        data = simplejson.dumps(data.result(), ignore_nan=True)
        return JsonResponse(simplejson.loads(data))


class LiveTestView(FormView):
    form_class = forms.ToTheMoonStrategyForm
    template_name = "backtests/livetest.html"

    def form_valid(self, form):
        context = self.get_context_data()
        exchange = form.cleaned_data['exchange']
        instrument = form.cleaned_data['instrument']
        period = form.cleaned_data['exchange_period']

        if form.cleaned_data['trading_fee']:
            trading_fee = float(form.cleaned_data['trading_fee'])
            wallet = Wallet(assets=100, currency=100, instrument=instrument, fee=trading_fee)
        else:
            wallet = Wallet(assets=100, currency=100, instrument=instrument)

        strategy = form.cleaned_data['strategy']
        mode = form.cleaned_data['mode']
        sma_period = form.cleaned_data['sma_period']
        ema_period = form.cleaned_data['ema_period']

        bot = Tradebot(
            mode=mode,
            wallet=wallet,
            strategy=strategy,
            instrument=instrument, period=int(period),
            sma_period=sma_period, ema_period=ema_period)
        data = bot.start_live_backtest()
        return render(self.request, self.template_name, context=context)

crumpet/backtests/templates/backtests/backtesting.html
{% extends "base.html" %}
{% load i18n %}

{% block styles-extra %}
    <link rel="stylesheet" href="/static/highcharts/highcharts.css">
{% endblock %}


{% block content %}
    <form id="ajax-form" method="POST" action="{% url "backtests:backtesting" %}" data-hook-ajax-form>
        {% csrf_token %}
        <div class="form-row">
            {% include "crumpet/includes/field.html" with field=form.exchange %}
            {% include "crumpet/includes/field.html" with field=form.mode %}
            {% include "crumpet/includes/field.html" with field=form.exchange_period %}
            {% include "crumpet/includes/field.html" with field=form.start_date %}
            {% include "crumpet/includes/field.html" with field=form.end_date %}
        </div>
        <div class="form-row">
            {% include "crumpet/includes/field.html" with field=form.instrument %}
            {% include "crumpet/includes/field.html" with field=form.strategy %}
            {% include "crumpet/includes/field.html" with field=form.trading_fee %}
            <button class="Btn" type="submit">{% trans "Start" %}</button>
        </div>
        <div class="form-row">
            {% include "crumpet/includes/field.html" with field=form.sma_period %}
            {% include "crumpet/includes/field.html" with field=form.ema_period %}
        </div>
    </form>

    <div id="container" class="highchart"></div>

{% endblock %}

crumpet/backtests/templates/backtests/livetest.html
{% extends "base.html" %}
{% load i18n %}

{% block styles-extra %}
    <link rel="stylesheet" href="/static/highcharts/highcharts.css">
{% endblock %}

{% block scripts %}

{% endblock %}


{% block content %}
    <div id="ajax-page" class="container">
        <form id="ajax-form" method="POST" action="{% url "backtests:livetest" %}">
            {% csrf_token %}
            <div class="form-row">
                {% include "crumpet/includes/field.html" with field=form.exchange %}
                {% include "crumpet/includes/field.html" with field=form.mode %}
                {% include "crumpet/includes/field.html" with field=form.exchange_period %}
            </div>
            <div class="form-row">
                {% include "crumpet/includes/field.html" with field=form.instrument %}
                {% include "crumpet/includes/field.html" with field=form.strategy %}
                {% include "crumpet/includes/field.html" with field=form.trading_fee %}
                <button class="Btn" type="submit">{% trans "Start" %}</button>
            </div>
            <div class="form-row">
                {% include "crumpet/includes/field.html" with field=form.sma_period %}
                {% include "crumpet/includes/field.html" with field=form.ema_period %}
            </div>
        </form>
    </div>
    {{ data }}
    <div id="container"></div>
    <script>
        Highcharts.chart('container', {

            title: {
                text: 'Solar Employment Growth by Sector, 2010-2016'
            },

            subtitle: {
                text: 'Source: thesolarfoundation.com'
            },

            yAxis: {
                title: {
                    text: 'Number of Employees'
                }
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle'
            },

            plotOptions: {
                series: {
                    pointStart: 2010
                }
            },

            series: [{
                name: 'Installation',
                data: [43934, 52503, 57177, 69658, 97031, 119931, 137133, 154175]
            }, {
                name: 'Manufacturing',
                data: [24916, 24064, 29742, 29851, 32490, 30282, 38121, 40434]
            }, {
                name: 'Sales & Distribution',
                data: [11744, 17722, 16005, 19771, 20185, 24377, 32147, 39387]
            }, {
                name: 'Project Development',
                data: [null, null, 7988, 12169, 15112, 22452, 34400, 34227]
            }, {
                name: 'Other',
                data: [12908, 5948, 8105, 11248, 8989, 11816, 18274, 18111]
            }]

        });
    </script>

{% endblock %}